# Install Nginx  
- name: Install nginx on Ubuntu
  ansible.builtin.apt:
    name: nginx
    state: present

# Create index.html using a template  
- name: create index.html
  ansible.builtin.template:
    src: index.html.j2 # Ensure you have the file "index.html.j2" in your templates directory
    dest: /var/www/html/index.html

# Create nginx configuration file  
- name: create nginx configuration
  ansible.builtin.copy:
    src: default.conf # Ensure you have the file "default.conf" in your files directory
    dest: /etc/nginx/sites-available/default
    mode: '0644'

# Ensure the configuration is enabled with a symbolic link  
- name: Enable nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
    force: yes

# Ensure nginx service is running and enabled  
- name: Ensure nginx service is running
  service:
    name: nginx
    state: started
    enabled: true
  notify:
    - restart nginx